readme.md
> The HoC to conditionally render a component based on a feature toggle's state. It accepts the feature toggle name and ~~a~~ an optional component to be rendered in case the feature is disabled.
=> docs(readme): fix grammar

.travis.yml, .yarnrc, lerna.json, package.json, packages/launchdarkly-wrapper/package.json, packages/launchdarkly-wrapper/rollup.config.js, packages/react-broadcast/package.json, packages/react-broadcast/rollup.config.js, packages/react-redux/package.json, packages/react-redux/rollup.config.js, packages/react/package.json, packages/react/rollup.config.js, yarn.lock
Integrate with yarn workspaces.
=> Refactor to use yarn workspaces

packages/react/modules/components/flags-subscription.js, packages/react/modules/components/flags-subscription.spec.js, readme.md
...from `willReceiveProps` as before.
=> Change `shouldInitialize` being called when `componentWillUpdate`

demo/src/App.js, packages/react-broadcast/modules/components/index.js, packages/react-broadcast/modules/components/inject-feature-toggle.js, packages/react-broadcast/modules/components/inject-feature-toggles.js, packages/react-broadcast/modules/components/with-feature-toggle.js, packages/react-broadcast/modules/index.js, packages/react-redux/modules/components/index.js, packages/react-redux/modules/components/inject-feature-toggle.js, packages/react-redux/modules/components/inject-feature-toggles.js, packages/react-redux/modules/components/with-feature-toggle.js, packages/react-redux/modules/index.js, packages/react/modules/components/__snapshots__/branch-untoggled.spec.js.snap, packages/react/modules/components/__snapshots__/inject-feature-toggle.spec.js.snap, packages/react/modules/components/branch-untoggled.js, packages/react/modules/components/branch-untoggled.spec.js, packages/react/modules/components/index.js, packages/react/modules/components/inject-feature-toggle.js, packages/react/modules/components/inject-feature-toggle.spec.js, packages/react/modules/components/inject-feature-toggles.js, packages/react/modules/index.js, readme.md
Adds a HoC to inject a single feature toggle.
- Refactors with-feature-toggle to use the component
- Renames requestedFeatureToggles
- Fixes tests of branchUntoggled while adjusting it to accept a flagName
Closes #10
=> ✨ Add `injectFeatureToggle` HoC

packages/react-broadcast/modules/components/__snapshots__/configure.spec.js.snap, packages/react-broadcast/modules/components/configure.js, packages/react-broadcast/modules/components/configure.spec.js, packages/react-redux/modules/components/__snapshots__/configure.spec.js.snap, packages/react-redux/modules/components/configure.js, packages/react-redux/modules/components/configure.spec.js, packages/react/modules/components/flags-subscription.js, packages/react/modules/components/flags-subscription.spec.js, readme.md
Closes #18
Being a breaking but useful change to simplify deferred initialisation.
Thanks to @dferber90 for proposing this.
=> 💣 Change `shouldInitialize` to be `prop` not callback

.travis.yml, demo/src/App.js, package.json, packages/launchdarkly-wrapper/modules/client.js, packages/launchdarkly-wrapper/modules/client.spec.js, packages/launchdarkly-wrapper/modules/index.js, packages/react-broadcast/modules/components/__snapshots__/configure.spec.js.snap, packages/react-broadcast/modules/components/configure.js, packages/react-broadcast/modules/components/configure.spec.js, packages/react-broadcast/modules/components/feature-toggled.js, packages/react-broadcast/modules/components/with-subscription.spec.js, packages/react-broadcast/package.json, packages/react-redux/modules/components/__snapshots__/configure.spec.js.snap, packages/react-redux/modules/components/configure.js, packages/react-redux/modules/components/configure.spec.js, packages/react-redux/modules/components/feature-toggled.js, packages/react-redux/modules/components/inject-feature-toggle.js, packages/react-redux/modules/components/inject-feature-toggles.js, packages/react-redux/package.json, packages/react/modules/components/flags-subscription.js, packages/react/modules/components/flags-subscription.spec.js, packages/react/modules/components/inject-feature-toggle.js, packages/react/modules/components/inject-feature-toggle.spec.js, packages/react/package.json, readme.md, yarn.lock
Closes #11 
Please refer to issue for feature desciption.
=> ✨ Add automatic changing user context when already initialized

readme.md
=> docs(readme): fix unpkg links

packages/launchdarkly-adapter/modules/adapter/adapter.js, packages/launchdarkly-adapter/modules/adapter/adapter.spec.js
This fixes the issue reported in #62.
=> Change user passed to launchdarkly-adapter not being spread

lerna.json, packages/react/modules/components/inject-feature-toggles/__snapshots__/inject-feature-toggles.spec.js.snap, packages/react/modules/components/inject-feature-toggles/inject-feature-toggles.js, packages/react/modules/components/inject-feature-toggles/inject-feature-toggles.spec.js, packages/react/package.json, readme.md
This should align the library with the workings or react-redux in this regard.
=> Add custom `areOwnPropsEqual` for `injectFeatureFlags`

packages/react-broadcast/modules/components/branch-on-feature-toggle/__snapshots__/branch-on-feature-toggle.spec.js.snap, packages/react-broadcast/modules/components/branch-on-feature-toggle/branch-on-feature-toggle.spec.js, packages/react-broadcast/modules/components/inject-feature-toggle/__snapshots__/inject-feature-toggle.spec.js.snap, packages/react-broadcast/modules/components/inject-feature-toggle/inject-feature-toggle.spec.js, packages/react-broadcast/modules/components/inject-feature-toggles/__snapshots__/inject-feature-toggles.spec.js.snap, packages/react-broadcast/modules/components/inject-feature-toggles/inject-feature-toggles.spec.js, packages/react-broadcast/modules/components/toggle-feature/__snapshots__/toggle-feature.spec.js.snap, packages/react-broadcast/modules/components/toggle-feature/toggle-feature.spec.js, packages/react-broadcast/package.json, packages/react-redux/modules/components/branch-on-feature-toggle/__snapshots__/branch-on-feature-toggle.spec.js.snap, packages/react-redux/modules/components/branch-on-feature-toggle/branch-on-feature-toggle.spec.js, packages/react-redux/modules/components/inject-feature-toggle/__snapshots__/inject-feature-toggle.spec.js.snap, packages/react-redux/modules/components/inject-feature-toggle/inject-feature-toggle.spec.js, packages/react-redux/modules/components/inject-feature-toggles/__snapshots__/inject-feature-toggles.spec.js.snap, packages/react-redux/modules/components/inject-feature-toggles/inject-feature-toggles.spec.js, packages/react-redux/modules/components/toggle-feature/__snapshots__/toggle-feature.spec.js.snap, packages/react-redux/modules/components/toggle-feature/toggle-feature.spec.js, yarn.lock
> This pull requests plans to add integration tests for most of our API.
I fiddled with adding real puppeteer based integration tests but that seems a bit too much.
=> Add integration tests (mounting) for components

commitlint.config.js, package.json
The object shape was has been fixed upstream: https://github.com/marionebl/commitlint/pull/213
=> fix(commitlint-config): fix parserPreset shape

.circleci/config.yml, package.json
It's almost sad and painful to do this but Renovate has super nice features: auto merging, scheduling and monorepo support.
=> Replace Greenkeeper with Renovate

demo/src/store.js, packages/react-redux/modules/store/enhancer/__snapshots__/enhancer.spec.js.snap, packages/react-redux/modules/store/enhancer/enhancer.js, packages/react-redux/modules/store/enhancer/enhancer.spec.js
This fixes a bug discussed in #131 when creating the store enhancer. It's a regression due to later refactorings which was not covert by tests. I have added more tests to avoid this to happen again.
In addition the demo example is updated on how to setup the store enhancer.
Thanks for @robinmakinson for reporting!
Closes #131
=> Fix react-redux store enhancer setup

readme.md
This aims to fix glitches in the docs which sneaked in with the last API improvements.
=> docs(readme): fix branchOnFeatureToggle usage

.flowconfig, package.json, packages/launchdarkly-adapter/package.json, packages/react-broadcast/package.json, packages/react-redux/package.json, packages/react/package.json, packages/splitio-adapter/package.json, yarn.lock
- Closes #253
- Closes #250
- Closes #252
- Closes #251
- Closes #240
- Closes #245
- Closes #248
- Closes #249
- Closes #239
- Closes #238
=> Update dependencies in batch

packages/react-broadcast/package.json, yarn.lock
We noticed some problems with the new version of create-react-context in our app. The library added the notion of change bits in the latest release. This is a fix until we figured out what the problem is.
=> fix(react-broadcast): context not updating in some cases

.circleci/config.yml
=> Fix caching `yarn` installs and saving them

packages/react-broadcast/modules/components/configure/with-flags.js, packages/react/modules/components/configure-adapter/configure-adapter.js, packages/react/modules/components/configure-adapter/configure-adapter.spec.js, packages/react/modules/components/configure-adapter/with-reconfiguration.js, readme.md
This applies some of feedback provided by @emmenko. Thanks!
https://github.com/tdeekens/flopflip/pull/280#discussion_r178456833
Maybe you can glimpse over to see if I got things right.
=> Improve `ReconfigureFlopflip`

packages/react/modules/components/configure-adapter/configure-adapter.js, packages/react/modules/components/configure-adapter/configure-adapter.spec.js
> The pull request closes an issue found by @Kerumen which made the adapter configure with false `adapterArgs` when deferring its configuration.
The issue #324 describes the problem more eloquently than I could.
One plausible solution is outlined in this PR. The adapter has to configure or reconfigure with queued (pending) or applied (from initial state) args. This situation is a bit "tricky" as we can not call `setState` in `componentDidUpdate` and also do not want the adapter be configured first with stale args and then with up-to-date ones.
=> Fix `ConfigureAdapter` with deferred configuration

readme.md
=> docs(readme): update title to `why you might use this`

.circleci/config.yml, package.json
=> feat(circle): run tests on node@11

packages/types/index.ts
Updated a few types to be more in line with tslint/eslint settings, fixed one type that was causing build issues (typescript assumed a variable's name was being changed to boolean)
=> update typings to fix build errors

packages/react-broadcast/modules/components/toggle-feature/toggle-feature.ts, packages/react-broadcast/modules/hooks/use-adapter-status/use-adapter-status.ts, packages/react-broadcast/modules/hooks/use-feature-toggle/use-feature-toggle.ts, packages/react-redux/modules/components/toggle-feature/toggle-feature.ts, packages/react/modules/components/branch-on-feature-toggle/branch-on-feature-toggle.ts, packages/react/modules/helpers/get-is-feature-enabled/get-is-feature-enabled.spec.js, packages/react/modules/helpers/get-is-feature-enabled/get-is-feature-enabled.ts, packages/react/modules/helpers/get-is-feature-enabled/index.ts, packages/react/modules/helpers/index.ts, packages/react/modules/helpers/is-feature-enabled/index.ts, packages/react/modules/index.ts
Adds use of `useDebugValue` too hooks where useful.
=> chore: add use-debug-value to hooks

packages/react-redux/modules/components/inject-feature-toggle/inject-feature-toggle.ts, packages/react-redux/modules/components/inject-feature-toggles/inject-feature-toggles.ts, packages/react-redux/modules/components/toggle-feature/toggle-feature.ts, packages/react-redux/modules/ducks/flags/flags.ts, packages/react-redux/modules/types.ts
=> fix(react-redux): state types in react-redux

packages/launchdarkly-adapter/modules/adapter/adapter.ts, packages/splitio-adapter/modules/adapter/adapter.ts
=> fix: signal isReady after flushing flags

packages/launchdarkly-adapter/modules/adapter/adapter.spec.js, packages/launchdarkly-adapter/modules/adapter/adapter.ts, packages/launchdarkly-adapter/package.json, yarn.lock
=> feat(launchdarkly-adapter): adds the ability to `flagsUpdateDelayMs`

packages/splitio-adapter/modules/adapter/adapter.ts
reconfigure splitio adapter if any user attribute changes.
previously it just reconfigured the adapter if the users key changed.
=> reconfigure splitio adapter if any attribute changes

packages/react-broadcast/package.json, packages/react-redux/package.json, packages/react/package.json
=> build: bump peer deps

packages/react-redux/modules/hooks/use-feature-toggle/index.ts, packages/react-redux/modules/hooks/use-feature-toggle/use-feature-toggle.spec.js, packages/react-redux/modules/hooks/use-feature-toggle/use-feature-toggle.ts
Adds useFeatureToggle to redux.
=> feat(react-redux): add use-feature-toggle

packages/react-broadcast/modules/components/toggle-feature/toggle-feature.tsx, packages/react-redux/modules/components/toggle-feature/toggle-feature.tsx
=> fix: use Omit to exclude object properties

packages/react-broadcast/modules/components/branch-on-feature-toggle/branch-on-feature-toggle.spec.js, packages/react-broadcast/modules/components/inject-feature-toggle/inject-feature-toggle.spec.js, packages/react-broadcast/modules/components/inject-feature-toggles/inject-feature-toggles.spec.js, packages/react-broadcast/modules/components/toggle-feature/toggle-feature.spec.js, packages/react-redux/modules/components/branch-on-feature-toggle/branch-on-feature-toggle.spec.js, packages/react-redux/modules/components/inject-feature-toggle/inject-feature-toggle.spec.js, packages/react-redux/modules/components/inject-feature-toggles/inject-feature-toggles.spec.js, packages/react-redux/modules/components/toggle-feature/toggle-feature.spec.js, packages/react-redux/modules/hooks/use-adapter-status/use-adapter-status.spec.js, packages/react-redux/modules/hooks/use-feature-toggle/use-feature-toggle.spec.js, packages/react-redux/modules/hooks/use-feature-toggles/use-feature-toggles.spec.js, packages/react-redux/modules/hooks/use-flag-variations/use-flag-variations.spec.js, packages/react/modules/components/toggle-feature/toggle-feature.spec.js, packages/react/modules/hocs/set-display-name/set-display-name.spec.js, packages/react/modules/hocs/wrap-display-name/wrap-display-name.spec.js, packages/react/modules/hooks/use-adapter-subscription/use-adapter-subscription.spec.js
Removes all beforeEach calls in tests using react testing library.
=> refactor: to remove before each

packages/localstorage-adapter/modules/adapter/adapter.ts
=> fix(local-storage-adapter): flag update logic

.eslintrc.yaml, packages/launchdarkly-adapter/modules/adapter/adapter.ts, packages/localstorage-adapter/modules/adapter/adapter.ts, packages/memory-adapter/modules/adapter/adapter.ts, packages/react-redux/modules/components/configure/configure.spec.js, packages/react/modules/components/toggle-feature/toggle-feature.ts, packages/react/package.json, packages/splitio-adapter/modules/adapter/adapter.ts, yarn.lock
=> refactor: clean up eslint

.eslintrc.yaml, package.json, packages/react-broadcast/modules/components/configure/configure.spec.js, packages/react-broadcast/modules/hooks/use-adapter-status/use-adapter-status.spec.js, packages/react-broadcast/modules/hooks/use-feature-toggle/use-feature-toggle.spec.js, packages/react-broadcast/modules/hooks/use-feature-toggles/use-feature-toggles.spec.js, packages/react-broadcast/modules/hooks/use-flag-variations/use-flag-variations.spec.js, packages/react-redux/modules/components/configure/configure.spec.js, packages/react-redux/modules/hooks/use-adapter-status/use-adapter-status.spec.js, packages/react-redux/modules/hooks/use-feature-toggle/use-feature-toggle.spec.js, packages/react-redux/modules/hooks/use-flag-variations/use-flag-variations.spec.js, packages/react/modules/components/configure-adapter/configure-adapter.spec.js, packages/react/modules/components/reconfigure-adapter/reconfigure-adapter.spec.js, packages/react/modules/hooks/use-adapter-subscription/use-adapter-subscription.spec.js, yarn.lock
=> test: add eslint plugin for react-testling-library

.changeset/poor-taxis-change.md, readme.md
Updates readme to include new features.
=> docs: update readme for new features

.changeset/empty-tools-suffer.md, packages/launchdarkly-adapter/modules/adapter/adapter.spec.js, packages/launchdarkly-adapter/modules/adapter/adapter.ts, packages/localstorage-adapter/modules/adapter/adapter.spec.js, packages/localstorage-adapter/modules/adapter/adapter.ts, packages/memory-adapter/modules/adapter/adapter.spec.js, packages/memory-adapter/modules/adapter/adapter.ts, packages/splitio-adapter/modules/adapter/adapter.ts, packages/types/index.ts
This pull request adds locked flags. More in the changelog.
=> feat: add the notion of locked flags and `updateFlags` to 3 out of 4 adapters

.changeset/brown-apricots-suffer.md, .eslintrc.yaml, packages/cypress-plugin/CHANGELOG.md, packages/cypress-plugin/index.ts, packages/cypress-plugin/modules/index.ts, packages/cypress-plugin/modules/plugin/index.ts, packages/cypress-plugin/modules/plugin/plugin.ts, packages/cypress-plugin/package.json, packages/cypress-plugin/readme.md, packages/cypress-plugin/tsconfig.json, tsconfig.json, yarn.lock
Adds a first version of the Cypress plugin.
=> feat: add cypress plugin

.changeset/dull-rats-beg.md, packages/cypress-plugin/modules/plugin/plugin.ts
=> fix(cypress-plugin): move to add commands

.changeset/giant-paws-serve.md, packages/cypress-plugin/modules/plugin/plugin.ts
=> fix(cypress-plugin): to wait for global

.changeset/gentle-guests-jump.md, packages/types/index.ts, packages/types/package.json
Fixes: https://github.com/tdeekens/flopflip/pull/1235/files#r484479306
=> fix(types): keep compatibility with v3

readme.md
=> Fix a typo in the readme for useFlagVariation

package.json, yarn.lock
=> fix: yarn.lock

.changeset/silly-seahorses-approve.md, packages/graphql-adapter/src/adapter/adapter.spec.js, packages/graphql-adapter/src/adapter/adapter.ts, packages/types/src/index.ts
=> feat: allow headers for adapter

.changeset/tasty-rats-know.md, package.json, packages/graphql-adapter/package.json, packages/launchdarkly-adapter/package.json, packages/localstorage-adapter/package.json, packages/localstorage-cache/package.json, packages/memory-adapter/package.json, packages/react-broadcast/package.json, packages/react-redux/package.json, packages/splitio-adapter/package.json, packages/test-utils/package.json, yarn.lock
Leftover from a preconstruct migration.
=> fix: remove unused read-pkg-* dependencies

.changeset/shaggy-trees-fold.md, packages/react-broadcast/src/hooks/use-adapter-status/use-adapter-status.ts, packages/react-redux/src/ducks/status/status.ts, packages/react/src/components/adapter-context/adapter-context.spec.js, packages/react/src/components/adapter-context/adapter-context.ts, packages/react/src/components/adapter-context/index.ts, packages/react/src/components/index.ts, packages/react/src/index.ts
=> fix: typo of selector for adapter context

.changeset/mean-years-push.md, packages/sessionstorage-cache/index.ts, packages/sessionstorage-cache/package.json, packages/sessionstorage-cache/src/cache/cache.spec.js, packages/sessionstorage-cache/src/cache/cache.ts, packages/sessionstorage-cache/src/cache/index.ts, packages/sessionstorage-cache/src/index.ts
=> feat(session-storage): add cache for session storage

.changeset/short-hairs-walk.md, package.json, packages/graphql-adapter/package.json, packages/graphql-adapter/src/adapter/adapter.spec.js, packages/graphql-adapter/src/adapter/adapter.ts, packages/types/src/index.ts
=> feat(graphql-adapter): add cache option

.changeset/fifty-spoons-watch.md, packages/adapter-utilities/CHANGELOG.md, packages/adapter-utilities/index.ts, packages/adapter-utilities/package.json, packages/adapter-utilities/readme.md, packages/adapter-utilities/src/denormalize-flag-name/denormalize-flag-name.spec.js, packages/adapter-utilities/src/denormalize-flag-name/denormalize-flag-name.ts, packages/adapter-utilities/src/denormalize-flag-name/index.ts, packages/adapter-utilities/src/expose-globally/expose-globally.spec.js, packages/adapter-utilities/src/expose-globally/expose-globally.ts, packages/adapter-utilities/src/expose-globally/index.ts, packages/adapter-utilities/src/index.ts, packages/adapter-utilities/src/normalize-flag/index.ts, packages/adapter-utilities/src/normalize-flag/normalize-flag.spec.js, packages/adapter-utilities/src/normalize-flag/normalize-flag.ts, packages/adapter-utilities/src/normalize-flags/index.ts, packages/adapter-utilities/src/normalize-flags/normalize-flags.spec.js, packages/adapter-utilities/src/normalize-flags/normalize-flags.ts, packages/graphql-adapter/src/adapter/adapter.ts, packages/launchdarkly-adapter/package.json, packages/launchdarkly-adapter/src/adapter/adapter.spec.js, packages/launchdarkly-adapter/src/adapter/adapter.ts, packages/localstorage-adapter/package.json, packages/localstorage-adapter/src/adapter/adapter.ts, packages/memory-adapter/package.json, packages/memory-adapter/src/adapter/adapter.ts, packages/splitio-adapter/package.json, packages/splitio-adapter/src/adapter/adapter.spec.js, packages/splitio-adapter/src/adapter/adapter.ts
=> refactor: add adapter utilities

.changeset/tall-dolphins-melt.md, packages/graphql-adapter/package.json, packages/react-broadcast/package.json, packages/react-redux/package.json, packages/react/package.json, yarn.lock
=> chore: clean up deps

.changeset/rare-avocados-shout.md, packages/graphql-adapter/src/adapter/adapter.ts, packages/launchdarkly-adapter/src/adapter/adapter.ts, packages/localstorage-adapter/src/adapter/adapter.ts, packages/memory-adapter/src/adapter/adapter.ts, packages/splitio-adapter/src/adapter/adapter.ts, packages/types/src/index.ts
=> refactor: expose helpers on adapter

.changeset/red-pens-cough.md, packages/graphql-adapter/src/adapter/adapter.ts, packages/launchdarkly-adapter/src/adapter/adapter.ts, packages/localstorage-adapter/src/adapter/adapter.ts, packages/memory-adapter/src/adapter/adapter.ts, packages/splitio-adapter/src/adapter/adapter.ts, packages/types/src/index.ts, tsconfig.json
=> refactor: adapters to use instance variables

.changeset/brave-spoons-refuse.md, demo/src/App.js, packages/adapter-utilities/src/expose-globally/expose-globally.spec.js, packages/adapter-utilities/src/expose-globally/expose-globally.ts, packages/graphql-adapter/src/adapter/adapter.spec.js, packages/graphql-adapter/src/adapter/adapter.ts, packages/graphql-adapter/src/adapter/index.ts, packages/graphql-adapter/src/index.ts, packages/launchdarkly-adapter/src/adapter/adapter.spec.js, packages/launchdarkly-adapter/src/adapter/adapter.ts, packages/launchdarkly-adapter/src/adapter/index.ts, packages/launchdarkly-adapter/src/index.ts, packages/localstorage-adapter/src/adapter/adapter.spec.js, packages/localstorage-adapter/src/adapter/adapter.ts, packages/localstorage-adapter/src/adapter/index.ts, packages/localstorage-adapter/src/index.ts, packages/memory-adapter/src/adapter/adapter.spec.js, packages/memory-adapter/src/adapter/adapter.ts, packages/memory-adapter/src/adapter/index.ts, packages/memory-adapter/src/index.ts, packages/react-broadcast/src/components/configure/configure.spec.js, packages/react-redux/src/components/configure/configure.spec.js, packages/splitio-adapter/src/adapter/adapter.spec.js, packages/splitio-adapter/src/adapter/adapter.ts, packages/test-utils/src/index.js, readme.md
=> refactor: updateFlags to be only on adapter

.changeset/seven-hairs-admire.md, packages/react-broadcast/src/components/configure/configure.tsx, packages/react-broadcast/src/hocs/branch-on-feature-toggle/branch-on-feature-toggle.tsx, packages/react-broadcast/src/hocs/inject-feature-toggle/inject-feature-toggle.tsx, packages/react-broadcast/src/hocs/inject-feature-toggles/inject-feature-toggles.tsx, packages/react-redux/src/hocs/branch-on-feature-toggle/branch-on-feature-toggle.tsx, packages/react-redux/src/hocs/inject-feature-toggle/inject-feature-toggle.tsx, packages/react-redux/src/hocs/inject-feature-toggles/inject-feature-toggles.tsx, packages/react/src/components/configure-adapter/configure-adapter.tsx, packages/react/src/components/reconfigure-adapter/reconfigure-adapter.ts, packages/react/src/components/toggle-feature/toggle-feature.ts, packages/react/src/hocs/set-display-name/set-display-name.ts, packages/react/src/hocs/wrap-display-name/wrap-display-name.ts
=> refactor: to change import * style

.changeset/eight-hounds-cheat.md, packages/react-broadcast/src/hocs/branch-on-feature-toggle/branch-on-feature-toggle.tsx, packages/react-broadcast/src/hocs/inject-feature-toggle/inject-feature-toggle.tsx, packages/react-broadcast/src/hocs/inject-feature-toggles/inject-feature-toggles.tsx, packages/react-redux/src/hocs/branch-on-feature-toggle/branch-on-feature-toggle.tsx, packages/react-redux/src/hocs/inject-feature-toggle/inject-feature-toggle.tsx, packages/react-redux/src/hocs/inject-feature-toggles/inject-feature-toggles.tsx
=> fix: to use record with unknown over object

.changeset/nasty-wasps-turn.md, packages/graphql-adapter/src/adapter/adapter.ts, packages/launchdarkly-adapter/src/adapter/adapter.ts, packages/localstorage-adapter/src/adapter/adapter.ts, packages/memory-adapter/src/adapter/adapter.ts, packages/splitio-adapter/src/adapter/adapter.ts
=> refactor: homogenize adapters

.changeset/pretty-spoons-hunt.md, packages/combine-adapters/src/adapter/adapter.ts, packages/types/src/index.ts
=> fix(combine-adapters): improve typings

.changeset/pink-games-yawn.md, packages/react-broadcast/src/hooks/use-feature-toggle/use-feature-toggle.ts, packages/react-broadcast/src/hooks/use-feature-toggles/use-feature-toggles.ts, packages/react-broadcast/src/hooks/use-flag-variations/use-flag-variations.ts, packages/react-redux/src/hooks/use-feature-toggle/use-feature-toggle.ts, packages/react-redux/src/hooks/use-feature-toggles/use-feature-toggles.ts, packages/react-redux/src/hooks/use-flag-variations/use-flag-variations.ts, packages/react/src/helpers/get-flag-variation/get-flag-variation.spec.js, packages/react/src/helpers/get-flag-variation/get-flag-variation.ts, packages/react/src/helpers/get-is-feature-enabled/get-is-feature-enabled.spec.js, packages/react/src/helpers/get-is-feature-enabled/get-is-feature-enabled.ts, packages/types/src/index.ts
=> feat: add support for number json

.changeset/nasty-lizards-cross.md, packages/graphql-adapter/src/adapter/adapter.spec.js, packages/graphql-adapter/src/adapter/adapter.ts, packages/launchdarkly-adapter/src/adapter/adapter.spec.js, packages/launchdarkly-adapter/src/adapter/adapter.ts, packages/localstorage-adapter/src/adapter/adapter.ts, packages/splitio-adapter/src/adapter/adapter.spec.js, packages/splitio-adapter/src/adapter/adapter.ts, packages/types/src/index.ts, readme.md
=> refactor(adapters): to split out sdk options

.changeset/mean-carpets-decide.md, packages/graphql-adapter/src/adapter/adapter.ts, packages/launchdarkly-adapter/src/adapter/adapter.ts, packages/localstorage-adapter/src/adapter/adapter.ts, packages/memory-adapter/src/adapter/adapter.ts, packages/react/src/components/configure-adapter/helpers.ts, packages/react/src/components/reconfigure-adapter/reconfigure-adapter.ts, packages/splitio-adapter/src/adapter/adapter.ts, packages/types/src/index.ts
=> refactor: to type TUser to be generic

.changeset/sour-laws-sort.md, package.json, packages/adapter-utilities/package.json, packages/combine-adapters/package.json, packages/cypress-plugin/package.json, packages/graphql-adapter/package.json, packages/launchdarkly-adapter/package.json, packages/localstorage-adapter/package.json, packages/memory-adapter/package.json, packages/react-broadcast/package.json, packages/react-redux/package.json, packages/react/package.json, packages/splitio-adapter/package.json, packages/types/package.json, yarn.lock
=> chore: add manypkg for validation for workspaces

.changeset/eight-pots-knock.md, packages/types/src/index.ts
=> fix: typing of combined adapter args

packages/types/src/index.ts
=> fix: allow passing additional user generic

.changeset/five-mangos-drop.md, packages/types/src/index.ts
=> fix: to have different user type per adapter

packages/http-adapter/CHANGELOG.md, packages/http-adapter/index.ts, packages/http-adapter/package.json, packages/http-adapter/readme.md, packages/http-adapter/src/adapter/adapter.spec.js, packages/http-adapter/src/adapter/adapter.ts, packages/http-adapter/src/adapter/index.ts, packages/http-adapter/src/index.ts, packages/types/src/index.ts
=> feat(http-adapter): add new http-adapter

.changeset/modern-taxis-camp.md, packages/types/src/index.ts
=> fix: return type of execute

.changeset/four-coats-hang.md, packages/combine-adapters/src/adapter/adapter.spec.js, packages/combine-adapters/src/adapter/adapter.ts, packages/react-broadcast/src/components/configure/configure.spec.js, packages/react-broadcast/src/components/toggle-feature/toggle-feature.spec.js, packages/react-broadcast/src/hocs/branch-on-feature-toggle/branch-on-feature-toggle.spec.js, packages/react-broadcast/src/hocs/inject-feature-toggle/inject-feature-toggle.spec.js, packages/react-broadcast/src/hocs/inject-feature-toggles/inject-feature-toggles.spec.js, packages/react-broadcast/src/hooks/use-adapter-status/use-adapter-status.spec.js, packages/react-broadcast/src/hooks/use-feature-toggle/use-feature-toggle.spec.js, packages/react-broadcast/src/hooks/use-feature-toggles/use-feature-toggles.spec.js, packages/react-broadcast/src/hooks/use-flag-variation/use-flag-variation.spec.js, packages/react-broadcast/src/hooks/use-flag-variations/use-flag-variations.spec.js, packages/react-redux/src/components/configure/configure.spec.js, packages/react-redux/src/components/toggle-feature/toggle-feature.spec.js, packages/react-redux/src/hocs/branch-on-feature-toggle/branch-on-feature-toggle.spec.js, packages/react-redux/src/hocs/inject-feature-toggle/inject-feature-toggle.spec.js, packages/react-redux/src/hocs/inject-feature-toggles/inject-feature-toggles.spec.js, packages/react-redux/src/hooks/use-adapter-status/use-adapter-status.spec.js, packages/react-redux/src/hooks/use-feature-toggle/use-feature-toggle.spec.js, packages/react-redux/src/hooks/use-flag-variation/use-flag-variation.spec.js, packages/react-redux/src/hooks/use-flag-variations/use-flag-variations.spec.js, packages/react/src/components/configure-adapter/configure-adapter.spec.js, packages/react/src/components/reconfigure-adapter/reconfigure-adapter.spec.js, packages/react/src/components/toggle-feature/toggle-feature.spec.js, packages/react/src/hooks/use-adapter-subscription/use-adapter-subscription.spec.js
=> refactor: to use screen over rendered

.github/workflows/lockfile.yml
=> feat(ci): add yarn lockfile analysis

.changeset/early-readers-heal.md, packages/react-broadcast/src/components/configure/configure.tsx
add getServerSnapshot so that react gets a server snapshot
closes #1658
=> fix: add getServerSnapshot

.browserslistrc, .changeset/tame-planets-think.md, babel.config.js, readme.md
=> refactor: to change browser list

.changeset/ninety-nails-teach.md, packages/combine-adapters/src/adapter/adapter.spec.js, packages/combine-adapters/src/adapter/adapter.ts
=> fix(combine-adapters): to not be stuck in configuring state

.changeset/real-carpets-admire.md, packages/react-broadcast/src/components/test-provider/test-provider.tsx, packages/react/src/components/adapter-context/adapter-context.ts
Otherwise tests which expect on some adapter state may fail.
=> fix: test-provider to have configuration state for all adapters

.changeset/big-rings-relax.md, packages/launchdarkly-adapter/package.json, packages/launchdarkly-adapter/src/adapter/adapter.ts, packages/types/src/index.ts, pnpm-lock.yaml
Just an attempt to incorporate caching as we have for the http/graphql adapters.
=> feat: allow caching in launchdarkly adapter

.changeset/nice-tools-live.md, packages/graphql-adapter/src/adapter/adapter.spec.js, packages/graphql-adapter/src/adapter/adapter.ts, packages/http-adapter/src/adapter/adapter.spec.js, packages/http-adapter/src/adapter/adapter.ts, packages/launchdarkly-adapter/src/adapter/adapter.ts
Otherwise the anonymous property is missing.
=> fix: needless reconfiguration

.changeset/khaki-eyes-applaud.md, packages/launchdarkly-adapter/src/adapter/adapter.ts
=> Fix to cache normalized flags

.changeset/new-spoons-camp.md, packages/launchdarkly-adapter/src/adapter/cache.ts
=> refactor: to restore cached flags leaner

.changeset/angry-apes-add.md, packages/launchdarkly-adapter/src/adapter/cache.ts
=> fix: restoring cached flags

.changeset/early-shoes-listen.md, packages/launchdarkly-adapter/src/adapter/cache.ts
=> refactor: add return type

.changeset/red-dancers-sort.md, packages/launchdarkly-adapter/src/adapter/cache.ts
=> fix: path to reference for flag values

.changeset/five-carpets-begin.md, packages/http-adapter/src/adapter/adapter.spec.js, packages/http-adapter/src/adapter/adapter.ts
=> Fix the refetching flags

.changeset/violet-books-behave.md, packages/http-adapter/src/adapter/adapter.ts
=> Http adapter/fix to broadcast

.changeset/slow-pets-think.md, packages/combine-adapters/src/adapter/adapter.ts, packages/graphql-adapter/src/adapter/adapter.ts, packages/http-adapter/src/adapter/adapter.ts, packages/launchdarkly-adapter/src/adapter/adapter.spec.js, packages/launchdarkly-adapter/src/adapter/adapter.ts, packages/localstorage-adapter/src/adapter/adapter.spec.js, packages/localstorage-adapter/src/adapter/adapter.ts, packages/memory-adapter/src/adapter/adapter.ts, packages/splitio-adapter/src/adapter/adapter.ts, packages/types/src/index.ts
Centralize emitting logic for events in adapter.
=> refactor: adapters to emit function

.changeset/curly-actors-explode.md, packages/launchdarkly-adapter/src/adapter.ts, packages/types/src/index.ts
Closes https://github.com/tdeekens/flopflip/issues/1986
Getting a good recommended timeout is "hard". LD doesn't state one but says it shouldn't be high.
=> feat(ld): allow initialization timeout

.changeset/five-bulldogs-tease.md, package.json, packages/react-broadcast/package.json, packages/react-redux/package.json, packages/react/package.json, packages/types/package.json, pnpm-lock.yaml, tooling/test-utils/package.json
=> Require react v18+

vitest.shared.ts
=> test: to use automatic runtime finally

packages/react-redux/CHANGELOG.md
Fix typo to resolve semantic error.
Was updating flopflip packages for a project and noticed this sentence in the change log that was missing some critical wording regarding what the user needs to do going forward.
Documentation change with no side effects.
=> Update @flopflip/react-redux@12.0.0 CHANGELOG.md
