- packages/react/modules/components/flags-subscription.js
- packages/react/modules/components/flags-subscription.spec.js
- readme.md
This helps `shouldInitialize` to remain pure and to not get mixed up in the order of lifecycle methods.
> Fixes `shouldInitialize` receiving user as argument

- packages/react-broadcast/modules/components/configure.js
- packages/react-redux/modules/components/configure.js
- packages/react/modules/components/flags-subscription.js
> This removes the `clientSideId` being a required prop.
This `clientSideId` generally has to be defined when setting up the `ld-wrapper`. However, the library allows deferring this. In cases where an application does not yet know the users `key` for instance - due to loading - we wait until `shouldInitialize` is `true` to then set up things. The same might hold for the `clientSideId`.
> Remove clientSideId being a required prop

- package.json
- packages/react/modules/components/__snapshots__/feature-toggled.spec.js.snap
- packages/react/modules/components/feature-toggled.js
- packages/react/modules/components/feature-toggled.spec.js
- readme.md
> Refactors `FeatureToggeld` to be more relaxed on what it accepts as arguments.
Before
```jsx
<Featuretoggled flag="foo" untoggledComponent={UntoggledComponent}>
<Yay />
</Featuretoggled>
```
After
```jsx
<Featuretoggled flag="foo" untoggledComponent={UntoggledComponent}>
<Yay />
</Featuretoggled>
```
```jsx
<Featuretoggled flag="foo" untoggledComponent={UntoggledComponent}>
{() => <Yay />}
</Featuretoggled>
```
```jsx
<Featuretoggled flag="foo" untoggledComponent={UntoggledComponent} toggledComponent={ToggledComponent} />
```
```jsx
<Featuretoggled flag="foo" untoggledComponent={UntoggledComponent} render={({ isFeatureEnabled }) => <div />} />
```
> FeatureToggled to accept node or function for togged/untoggled

- demo/package.json
- demo/src/App.js
- packages/launchdarkly-adapter/modules/adapter.spec.js
- packages/launchdarkly-adapter/readme.md
- packages/memory-adapter/modules/adapter.js
- packages/memory-adapter/modules/adapter.spec.js
- packages/memory-adapter/modules/index.js
- packages/memory-adapter/package.json
- packages/memory-adapter/readme.md
- packages/memory-adapter/rollup.config.js
- packages/react-broadcast/readme.md
- packages/react-redux/readme.md
- readme.md
> This adds a simple in memory adapter for `flopflip`.
The adapter should be configured like any other adapter
```js
import adapter from '@flopflip/memory-adapter';
import { ConfigureFlopFlip } from '@flopflip/react-redux';
<ConfigureFlopflip adapter={adapter} adapterArgs={{ user }}>
<App />
</ConfigureFlopflip>
```
Somewhere else in your app you can programmatically toggle things on/off throughout our application.
```js
import { updateFlags } from '@flopflip/memory-adapter';
updateFlags({ fooFeature: true })
```
...which will notify any listening component in `react-broadcast` or `react-redux` like `FeatureToggled` or `withFeatureToggle`.
> Add an in memory adapter

- packages/splitio-adapter/modules/adapter/adapter.js
- packages/splitio-adapter/modules/adapter/adapter.spec.js
- packages/splitio-adapter/modules/adapter/index.js
- packages/splitio-adapter/modules/index.js
- packages/splitio-adapter/package.json
- packages/splitio-adapter/readme.md
- readme.md
- yarn.lock
This add the adapter for the split.io service (https://www.split.io/).
I adapted it from the LaunchDarkly adapter with few differences:
* There is no boolean flags so I converted `on` and `off` to boolean and let others pass through
* 2 calls have to be made to get first, the flags, then, the values
* There is no concept of `user` because split.io uses segments, but you can pass a map of attributes in the `getTreatment[s]` calls so I adapted this concept with the notion of `user` the flipflop's API has
* The listener doesn't returns changed flags. It only indicates a change. So flags must be refetched.
Finally, the split.io SDK returns a `factory` where you can get either the `.client()` or the `.manager()`. I had trouble to test this because I'm pretty new to Jest so I let 2 tests failed …
> Add splitio adapter

- packages/splitio-adapter/modules/adapter/adapter.js
- packages/splitio-adapter/modules/adapter/adapter.spec.js
- packages/splitio-adapter/modules/adapter/index.js
- packages/splitio-adapter/modules/index.js
- packages/splitio-adapter/package.json
- packages/splitio-adapter/readme.md
- readme.md
- rollup.config.js
- yarn.lock
Thanks for @Kerumen we will soon have an adapter for splitio. This branch aims to fix the last issues with build setup, documentation etc.
> Add `splitio-adapter` package

- packages/launchdarkly-adapter/modules/index.js
- packages/localstorage-adapter/modules/index.js
- packages/memory-adapter/modules/index.js
- packages/react-broadcast/modules/index.js
- packages/react-redux/modules/index.js
- packages/react/modules/index.js
- packages/splitio-adapter/modules/index.js
🚨 The currently published version of the `splitio-adapter` is broken because it doesn't export the version from `package.json` and the `VERSION` replacement got removed some commits ago.
I also cleaned the remainings `const version = VERSION;` useless now.
> Fix version export in splitio-adapter

- packages/launchdarkly-adapter/modules/adapter/adapter.js
- packages/launchdarkly-adapter/package.json
- packages/splitio-adapter/modules/adapter/adapter.js
- packages/splitio-adapter/package.json
We just had the same build problem you had when bundling all the dependencies. The problem is that Sindre Sorhus doesn't love the browser and target node. So he doesn't compile his modules.
We need to use this for the web and we use create-react-app. CRA doesn't compile the `node_modules` (https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify).
Hence, I switched to `lodash.camelcase` which behaves exactly the same. I let you revert the special rollup config you did if you want to.
> Replace camelcase module by Lodash camelcase

- packages/react-broadcast/modules/components/feature-toggled/feature-toggled.js
- packages/react-broadcast/modules/components/inject-feature-toggle/inject-feature-toggle.js
- packages/react-broadcast/modules/components/inject-feature-toggles/inject-feature-toggles.js
- packages/react-redux/modules/components/inject-feature-toggle/inject-feature-toggle.js
- packages/react-redux/modules/components/inject-feature-toggles/inject-feature-toggles.js
- packages/react-redux/modules/components/inject-feature-toggles/inject-feature-toggles.spec.js
- packages/react-redux/modules/ducks/flags/flags.js
- packages/react-redux/modules/ducks/flags/flags.spec.js
- packages/react-redux/modules/ducks/flags/index.js
- packages/react-redux/modules/ducks/index.js
- packages/react-redux/modules/index.js
- packages/react-redux/package.json
- packages/react/modules/components/inject-feature-toggle/__snapshots__/inject-feature-toggle.spec.js.snap
- packages/react/modules/components/inject-feature-toggle/inject-feature-toggle.js
- packages/react/modules/components/inject-feature-toggle/inject-feature-toggle.spec.js
- packages/react/modules/components/inject-feature-toggles/__snapshots__/inject-feature-toggles.spec.js.snap
- packages/react/modules/components/inject-feature-toggles/inject-feature-toggles.js
- packages/react/modules/components/inject-feature-toggles/inject-feature-toggles.spec.js
- packages/react/modules/constants.js
- packages/react/modules/index.js
- readme.md
> This pull request adds selectors and exposes them form the `react-redux` package.
With request from #68 we decided to refactor the package to use selectors for all flags and a single flag while also exposing them.
```js
const mapStateToProps = state => {
someOtherState: state.someOtherState,
isFeatureOn: selectFeatureFlag(state)('fooFlagName')
}
export default connect(mapStateToProps)(FooComponent)
```
Closes #68
> Add `selectFeatureFlags` and `selectFeatureFlag` selectors

- packages/react/modules/components/inject-feature-toggles/__snapshots__/inject-feature-toggles.spec.js.snap
- packages/react/modules/components/inject-feature-toggles/inject-feature-toggles.js
In #75 it was outlines that due to the fact that we treat flags as immutable (creating referentially different ones) we also re-render components wastefully which compose with `injectFeatureToggles`. 
This pull request attempts to reduce the wasteful renders by using `onlyUpdateForKeys` by `recompose`. It restricts re-renders only by the `flagNames` requested..
Closes #76
> fix(react): so that injectFeatureToggles only updates for keys

- packages/react/modules/components/feature-toggled/__snapshots__/feature-toggled.spec.js.snap
- packages/react/modules/components/feature-toggled/feature-toggled.js
- packages/react/modules/components/feature-toggled/feature-toggled.spec.js
This fixes the behaviour of our render props on `FeatureToggled`. Generally `render` should only be invoked whenever there is a match. Whereas `children` (whenever a function) should always be invoked with `props`. Sadly, we decided to take this the wrong way round. 
There might be no right way in this defacto but `react-router` serves as an example here and community homogeneity seems favourable.
> BREAKING(react): invoke children in any case, render on match

- packages/react-broadcast/modules/components/branch-on-feature-toggle/branch-on-feature-toggle.js
- packages/react-broadcast/modules/components/configure/configure.js
- packages/react-broadcast/package.json
- packages/react-broadcast/types/index.d.ts
- packages/react-redux/modules/components/branch-on-feature-toggle/branch-on-feature-toggle.js
- packages/react-redux/package.json
- packages/react-redux/types/index.d.ts
- packages/react/modules/components/toggle-feature/toggle-feature.js
- packages/react/modules/types.js
After having migrated all code to flow-type I wanted to offer TypeScript definitions files.
Generally IDE support for TypeScript is quite advanced, many developers use VSCode and we can give inline type hints.
I don't mind hosting the definitions linked by a `package.json` entry. Types don't get out of sync and don't have to be versioned in another repository. While developers would have to install `@types/flipflip/react-broadcast` mostly manually. All too much maintenance overhead for me instead of just keeping them here.
Flow has also has a `flow-typed` repository with types. However, I've seen a little amount of developers having flow setup in their IDE either installing types or expecting IDE integrations to give hints. I could probably also just link or re-export the internally held …
> Add TypeScript definitions for `react-redux` and `react-broadcast`

- packages/splitio-adapter/modules/adapter/adapter.js
- packages/splitio-adapter/modules/adapter/adapter.spec.js
The splitio JS client can be configured with a lot of options (https://docs.split.io/docs/javascript-sdk-overview#section-configuration).
This brings the ability to pass an `adapterArgs` prop with the options we want to configure.
```
<ConfigureFlopFlip
adapter={adapter}
adapterArgs={{ authorizationKey, user, core: { labelsEnabled: false } }}
>
```
If you want to nest this behind an object key (like `adapterConfig` or something), let me know!
> Pass args to configure the splitio client

- .circleci/config.yml
- package.json
Run scripts were disabled as lerna died otherwise on CI with too much concurrency. The work around was to orchestrate more manually. However this now breaks for adding BuckleScript bindings. This is an attempt to fix the issue.
> Fixes CircleCI to run run-scripts

- .circleci/config.yml
- .yarnrc
- package.json
When using yarn workspaces, it's not necessary to run `lerna bootstrap`
as it might get into an infinite loop when execute on postinstall step.
See https://github.com/lerna/lerna/issues/1125 and related issues
In case the prepublish and prepare script hooks need to be executed, you
can simply trigger those "manually" in the postinstall script.
```
"postinstall": "check-node-version --package --print && lerna run prepublish && lerna run prepare"
```
Side note: is the `build` step supposed to be executed separately from the "installation" step?
```
$ yarn
$ yarn build
```
> Remove unnecessary `lerna bootstrap` command

- .babelrc
- package.json
- packages/react-broadcast/modules/components/branch-on-feature-toggle/branch-on-feature-toggle.js
- packages/react-broadcast/modules/components/configure/configure.js
- packages/react-broadcast/modules/components/feature-toggled/index.js
- packages/react-broadcast/modules/components/inject-feature-toggle/inject-feature-toggle.js
- packages/react-broadcast/modules/components/inject-feature-toggles/inject-feature-toggles.js
- packages/react-broadcast/modules/components/with-flag-subscription/with-flag-subscription.js
- packages/react-redux/modules/components/branch-on-feature-toggle/branch-on-feature-toggle.js
- packages/react-redux/modules/components/configure/configure.js
- packages/react-redux/modules/components/feature-toggled/index.js
- packages/react-redux/modules/components/inject-feature-toggle/inject-feature-toggle.js
- packages/react-redux/modules/components/inject-feature-toggles/inject-feature-toggles.js
- packages/react/modules/components/branch-on-feature-toggle/branch-on-feature-toggle.js
- packages/react/modules/components/flags-subscription/flags-subscription.js
- packages/react/modules/components/inject-feature-toggle/inject-feature-toggle.js
- packages/react/modules/components/inject-feature-toggles/inject-feature-toggles.js
- packages/react/modules/components/switch-feature/switch-feature.js
- packages/react/modules/components/toggle-feature/toggle-feature.js
- rollup.config.js
- yarn.lock
This literally ended a hour long journey.
In combination with rollup importing `import * as React from 'react'` instead of `import React from 'react'` causes an UMD bundle get receive code in `"var React__default = React['default'];"` rather than `"var React__default = 'default' in React ? React['default'] : React;"` in the factory of the UMD bundle. Causing the my library to not work. Being aware that I could import types separately from the packages which is not mentioned in the docs of flow solved this for me.
> Fix UMD builds caused by flow and rollup in combination with imports

- packages/launchdarkly-adapter/modules/adapter/adapter.js
- packages/launchdarkly-adapter/modules/adapter/adapter.spec.js
The `js-client` of LaunchDarkly recently update its API with `waitUntilReady` and `identify` to return a Promise. This can simplify the adapter a little.
> Update `launchdarkly-adapter` to utilize updated API of LD `js-client`

- packages/launchdarkly-adapter/modules/adapter/adapter.js
- packages/splitio-adapter/modules/adapter/adapter.js
This pull request aims to fix a bug reported in #187. When reconfiguring with a non-existing user the check would cause the adapter to throw.
Closes #195
> Fix launchdarkly splitio adapter reconfiguring without user

- packages/react/modules/helpers/is-feature-enabled/is-feature-enabled.js
- packages/react/modules/helpers/is-feature-enabled/is-feature-enabled.spec.js
- packages/react/package.json
- readme.md
> This pull request aims to to target a discussion around unexpected behaviour of the library when passing non-normalised flags.
I am still not too sure if I would like to add a `skipFlagNormalization` prop to `<ConfigureFlopflip> yet. In mean time - and even after - I think it's worthwhile to provide descriptive warnings to the user whenever the library encounters a situation where it might behave other than anticipated.
This means:
- Whenever a passed flag - either in `react-broadcast` or `react-redux` ends up in `isFeatureEnabled`
- and the flag name does not seem normalized
- then we warn the user with a reference to the respective readme section
Again, this same behaviour should exist whenever a `skipFlagNormalization` prop is added. However I see some problems with that still which …
> Add reference when non normalised flag names are encountered

- packages/react-broadcast/typings/index.d.ts
- packages/react-redux/typings/index.d.ts
- packages/types/index.d.ts
Builds upon #244 and closes #244 to fix typings for ToggleFeature.
> fix(react-*): TypeScript typings for ToggleFeature

- packages/launchdarkly-adapter/modules/adapter/adapter.js
- packages/launchdarkly-adapter/modules/adapter/adapter.spec.js
Improves and fixes error handling when updating the user context before the adapter is ready.
- Now properly rejects the promise
- Early returns the function
- Added tests
> fix(launchdarkly-adapter): change of user context

- packages/launchdarkly-adapter/modules/adapter/adapter.js
- packages/launchdarkly-adapter/package.json
- yarn.lock
> Previously the user `key` property was used to determine reconfiguring the adapter.
This might not be intended as other user properties can also change about which LD needs to be notified in case they change on the client.
This pull request changes the equality check some key equality to a deep equals check via lodash (note we use lodash for all utils).
Closes #268
> Reconfigure `launchdarkly-adapter` on non deep equality of users

- packages/react/modules/components/configure-adapter/configure-adapter.js
- packages/react/modules/components/configure-adapter/configure-adapter.spec.js
- packages/react/modules/components/reconfigure-adapter/reconfigure-adapter.js
- packages/react/modules/components/reconfigure-adapter/reconfigure-adapter.spec.js
- readme.md
Changes
- `setAdapterArgs` -> `applyAdapterArgs`
- `unsetPendingAdapterArgs` -> `applyPendingAdapterArgs`
NOTE: I will sneak in a breaking change (it's Easter Sunday and nobody has downloaded the new version nor uses `ReconfigureFlopflip`. `exact` is now `shouldOverwrite`. Not it also defaults to the same `defaultProp`.
/cc @emmenko I think you would like this. Thanks for being persistent on renaming `exact`. I think that props should default to `false` which creates better APIs for components. Non-default behaviour is an opt-in by switching things to true.
> Improve method names in `ConfigureFlopflip`

- readme.md
Replace wrong `adapterArgs={(clientSideId, user)}` by `adapterArgs={{ clientSideId, user }}`
> Fix typo in `adapterArgs` in README

- demo/src/modules/index.js
- packages/react-redux/modules/ducks/flags/flags.js
- packages/react-redux/modules/ducks/flags/index.js
- packages/react-redux/modules/ducks/index.js
- packages/react-redux/modules/ducks/status/status.js
- packages/react-redux/modules/index.js
- readme.md
> This pull request implements a higher-order reducer for the `flopflipReducer` to allow passing in a `preloadedState`.
- Closes #369
This pull request contains the following:
1. Update to the readme
2. Adding and exporting a `createFlopflipReducer`
> Add a `createFlopflipReducer` for `preloadedState` through reducer

- readme.md
Trying to make it more clear that
1. LaunchDarkly is not needed to use this package
2. The different options you have for installing this package (store enhancer or context component)
I have a question about the following copy:
> Setup through a Redux store enhancer
> reducer & STATE_SLICE
Another way to configure flopflip is using a store enhancer. For this a flopflip reducer should be wired up with a combineReducers within your application in coordination with the STATE_SLICE which is used internally too to manage the location of the feature toggle states. **This setup eliminates the need to use ConfigureFlopFlip somewhere else in your application's component tree.**
however In issue #369 you said:
>  Lasly, the ConfigureFlopflip accepts defaultFlags too. This is also mentioned in the …
> Improve documentation for flopflip

- packages/launchdarkly-adapter/modules/adapter/adapter.js
- packages/launchdarkly-adapter/modules/adapter/adapter.spec.js
In their latest release the LaunchDarkly team deprecated the default export of the client favouring the named export. This adapts the client to that to avoid future breakage.
> Refactor LaunchDarkly adapter to use named exports

- packages/types/index.d.ts
The exported function is called `ConfigureFlopFlip` and not `ConfigureFlopflip`.
> TypeScript: correct casing of export ConfigureFlopFlip

- .flowconfig
- packages/memory-adapter/modules/adapter/adapter.js
- yarn.lock
It seems logical for an adapter which is controlled user land to reset when configure if invoked again. Maybe also for testing purposes.
> Fix memory-adapter to reset flags also on configure

- packages/launchdarkly-adapter/modules/adapter/adapter.js
- packages/launchdarkly-adapter/modules/adapter/adapter.spec.js
Closes #474 
This adds the ability to opt-out of the flags subscription by passing a `shouldSubcribeToFlagChanges: false` in the `adapterArgs` passed to `ConfigureFlopflip`.
> Add ability to opt-out of flag subscription of ld-adapter

- packages/memory-adapter/modules/adapter/adapter.js
- packages/memory-adapter/package.json
- yarn.lock
Maybe this pattern will move into all adapters. It seems that sometimes the same adapter must work with multiple ConfigureFlopflips. The memory-adapter is only a good example as it's often used for testing.
The ld and splitio adapter support this already has they have an internal event emitter in the sdks.
> feat(memory-adapter): to have event emitter

- packages/launchdarkly-adapter/modules/adapter/adapter.js
The `ld-client-js` has a concept of `options` we rebrand here to `clientOptions`. Those e.g. allow to disable the `fetchGoals` which reduces the http requests when not intending to perform A/B testing through the LD client with flopflip.
We think it's a good idea to support those options and pass them on to the underlying `ld-client`. 
The current version of the `ConfigureAdapter` in the `react` package already supports this as `adapterArgs` are a rather generic concept.
```jsx
<ConfigureAdapter adapter={ldAdapter} adapterArgs={{ 
clientSideId: 'foo', 
user: { id: 'bar' }, 
clientOptions: { fetchGoals: false } 
}}>
<App />
</ConfigureAdapter>
```
> Add support for client options to launchdarkly-adapater

- packages/react-broadcast/modules/hooks/index.js
- packages/react-broadcast/modules/hooks/use-feature-toggle/index.js
- packages/react-broadcast/modules/hooks/use-feature-toggle/use-feature-toggle.js
- packages/react-broadcast/modules/hooks/use-feature-toggle/use-feature-toggle.spec.js
- packages/react-broadcast/modules/index.js
This pull request adds a `useFeatureToggle(flagName: FlagName, flagVariation: FlagVariation)` React hook.
```js
import { useFeatureToggle } from '@flopflip/react-broadcast';
function ComponentWithFeatureToggle(props) {
const isFeatureEnabled = useFeatureToggle('myFeatureToggle');
return (
<h3>{props.title}<h3>
<p>
The feature is {isFeatureEnabled ? 'enabled' : 'disabled'}
</p>
);
}
```
This is just a small experiment how we flopflip's architecture could support a React hook. It is unclear to me how this could also be supported for `@flopflip/react-redux` without redux having a `useRedux` hook to use.
> Add useFeatureToggle react hook (forward compatible)

- packages/launchdarkly-adapter/modules/adapter/adapter.js
- packages/launchdarkly-adapter/modules/adapter/adapter.spec.js
- packages/launchdarkly-adapter/package.json
- packages/react-broadcast/modules/hooks/use-feature-toggle/use-feature-toggle.js
- packages/react-broadcast/modules/hooks/use-feature-toggle/use-feature-toggle.spec.js
- packages/react/modules/helpers/is-feature-enabled/is-feature-enabled.js
- packages/react/modules/helpers/is-feature-enabled/is-feature-enabled.spec.js
- packages/react/package.json
- yarn.lock
After `tiny-invariant` comes `tiny-warning`.
> refactor to use tiny-warning over warning

- packages/memory-adapter/modules/adapter/adapter.spec.js
- packages/memory-adapter/modules/adapter/adapter.ts
- packages/react-broadcast/modules/components/branch-on-feature-toggle/__snapshots__/branch-on-feature-toggle.spec.js.snap
- packages/react-broadcast/modules/components/inject-feature-toggle/__snapshots__/inject-feature-toggle.spec.js.snap
- packages/react-broadcast/modules/components/inject-feature-toggles/__snapshots__/inject-feature-toggles.spec.js.snap
- packages/react-broadcast/modules/components/toggle-feature/__snapshots__/toggle-feature.spec.js.snap
- packages/react-redux/modules/components/branch-on-feature-toggle/__snapshots__/branch-on-feature-toggle.spec.js.snap
- packages/react-redux/modules/components/inject-feature-toggle/__snapshots__/inject-feature-toggle.spec.js.snap
- packages/react-redux/modules/components/inject-feature-toggles/__snapshots__/inject-feature-toggles.spec.js.snap
- packages/react-redux/modules/components/toggle-feature/__snapshots__/toggle-feature.spec.js.snap
Adds a `setIsReady` to the `memory-adapter` which is often helpful when testing. 
```js
adapter.setIsReady({ isReady: false });
adapter.getIsReady() // <- false
```
Additionally the `onStatusStateChange` will be invoked.
> feat(memory-adapter): add setIsReady

- packages/react-broadcast/package.json
- packages/react-redux/modules/components/branch-on-feature-toggle/branch-on-feature-toggle.spec.js
- packages/react-redux/modules/components/inject-feature-toggle/inject-feature-toggle.spec.js
- packages/react-redux/modules/components/inject-feature-toggles/inject-feature-toggles.spec.js
- packages/react-redux/modules/components/toggle-feature/toggle-feature.spec.js
- packages/react-redux/test-utils/index.js
- yarn.lock
This is a follow up from #613 to avoid such things in the past. The store is not tested in integration and not mocked anymore.
> refactor(react-redux): to remove the mock store

- packages/react/modules/components/configure-adapter/with-reconfiguration.tsx
This fixes a regression introduced by 8.1.0. The AdapterContext now contains two values: `reconfigure` and `status`. Previously only one.
> fix(react): with-adapter-reconfiguration

- packages/react-broadcast/modules/hooks/index.ts
- packages/react-broadcast/modules/hooks/use-adapter-reconfiguration/index.ts
- packages/react-broadcast/modules/index.ts
- packages/react-redux/modules/hooks/index.ts
- packages/react-redux/modules/hooks/use-adapter-reconfiguration/index.ts
- packages/react-redux/modules/index.ts
- packages/react/modules/hooks/index.ts
- packages/react/modules/hooks/use-adapter-reconfiguration/index.ts
- packages/react/modules/hooks/use-adapter-reconfiguration/use-adapter-reconfiguration.spec.js
- packages/react/modules/hooks/use-adapter-reconfiguration/use-adapter-reconfiguration.ts
- packages/react/modules/index.ts
- readme.md
This pull request allows pulling the `reconfiguration` function from the context. This works on both the redux and broadcast variation of the library.
> feat(react): add `useAdapterReconfiguration`

- packages/launchdarkly-adapter/modules/adapter/adapter.spec.js
- packages/launchdarkly-adapter/modules/adapter/adapter.ts
- Closes #679 
This pull request intends to solve the issue with resolving configuration only with ready event when it succeeds.
> refactor(launchdarkly-adapter): to waitForInitialization

- readme.md
This pull request adds the so far undocumented options of the `@flopflip/launchdarkly-adapter`.
> docs(readme): add adapter options to readme

- packages/splitio-adapter/modules/adapter/adapter.spec.js
- packages/splitio-adapter/modules/adapter/adapter.ts
when calling reconfigure, destroy split.io client and recreate it with saved configuration
fixes #689
> fix: splitio-adapter reconfigure

- babel.config.js
- package.json
- yarn.lock
This could be considered breaking. However has the have a substitute in TypeScript types and had this remove before we won't release it as breaking again.
Essentially the plugin https://github.com/milesj/babel-plugin-typescript-to-proptypes fails to deduct some complex union types. This yields warnings in apps without any reason.
> chore: remove prop-types

- packages/react-broadcast/package.json
- packages/react-redux/package.json
- packages/react/modules/components/configure-adapter/configure-adapter.spec.js
- packages/react/modules/components/configure-adapter/configure-adapter.tsx
- packages/react/package.json
> chore: support only react >=16.3, rename deprecated lifecycle method

- packages/react-broadcast/modules/components/flags-context/flags-context.ts
- packages/react-broadcast/modules/hooks/use-adapter-status/use-adapter-status.ts
- packages/react-broadcast/modules/hooks/use-feature-toggle/use-feature-toggle.ts
- packages/react-broadcast/package.json
- packages/react/modules/components/adapter-context/adapter-context.ts
- packages/react/modules/hooks/use-adapter-reconfiguration/use-adapter-reconfiguration.ts
- packages/react/package.json
- yarn.lock
This pull request removes `create-react-context` possible now as we support only 16.3.
/cc @emmenko thanks!
> refactor: remove `create-react-context`

- packages/launchdarkly-adapter/modules/adapter/adapter.spec.js
- packages/launchdarkly-adapter/modules/adapter/adapter.ts
- packages/types/index.ts
This pull request allows passing `requestedFlags` to the `launchdarkly-adpter`.
Passing `requestedFlags` will change the flag setup so that `variation` is called over `allFlags` which allow using LDs long running flag detection.
> feat(launchdarkly-adapter): to allow passing flags

- packages/launchdarkly-adapter/modules/adapter/adapter.spec.js
- packages/launchdarkly-adapter/modules/adapter/adapter.ts
- packages/localstorage-adapter/modules/adapter/adapter.spec.js
- packages/localstorage-adapter/modules/adapter/adapter.ts
- packages/memory-adapter/modules/adapter/adapter.spec.js
- packages/memory-adapter/modules/adapter/adapter.ts
- packages/react/modules/components/inject-feature-toggle/inject-feature-toggle.ts
- packages/react/modules/components/inject-feature-toggles/utils.ts
- packages/react/modules/helpers/get-is-feature-enabled/get-is-feature-enabled.spec.js
- packages/react/modules/helpers/get-is-feature-enabled/get-is-feature-enabled.ts
- packages/react/modules/helpers/get-normalized-flag-name/get-normalized-flag-name.spec.js
- packages/react/modules/helpers/get-normalized-flag-name/get-normalized-flag-name.ts
- packages/react/modules/helpers/get-normalized-flag-name/index.ts
- packages/react/modules/helpers/index.ts
- packages/splitio-adapter/modules/adapter/adapter.spec.js
- packages/splitio-adapter/modules/adapter/adapter.ts
- readme.md
This pull request takes on #841 to normalise flags by default. 
I still have to reflect on the consequences of this and how to make adapters backwards compatible.
E.g. if you have non normalised flags in local storage we need to normalise to forward their value correctly.
I like this change but it's a bit more risky than it seems ;)
> refactor: to automatically normalise flags

- packages/launchdarkly-adapter/modules/adapter/adapter.ts
Flag updates fail as we subscribe with a normalized flag name not a denormalized one.
> fix(launchdarkly-adapter): to denormalize flag names

- packages/react/modules/components/configure-adapter/configure-adapter.tsx
- packages/types/index.ts
The type declaration of `ConfigureAdapterChildren` is not entirely correct.
The `ConfigureAdapter` component of the `react` package is typed with `children` being
```tsx
type ConfigureAdapterChildren = ({
isAdapterReady,
}: {
isAdapterReady: boolean;
}) => React.ReactNode | React.ReactNode | null;
```
which makes it to always be a function. As a consequence, passing a `ReactNode` as a child, results in a type error.
I think the mistake is in the syntax `=> React.ReactNode | React.ReactNode | null`, which hints that the **return type** of the function is either one of the listed types, instead of the `ConfigureAdapterChildren` type being etiher-or.
To fix that, I split the types so that the union is less ambiguous.
> fix(types): adapter children is either a node or a function

- packages/react-broadcast/modules/components/configure/configure.tsx
- packages/react-redux/modules/components/configure/configure.tsx
- packages/react/modules/components/configure-adapter/configure-adapter.tsx
- packages/types/index.ts
According to the types of `adapterArgs` prop, the `ConfigureFlopFlip` component currently requires the user to pass props such as `onStatusStateChange` and `onFlagsStateChange`.
As far as I understand, those props are only used internally and therefore do no need to be exposed to the `ConfigureFlopFlip` component.
> fix(types): do not expose event handlers to adapterArgs props

- packages/react-broadcast/modules/components/configure/configure.tsx
- packages/react/modules/helpers/create-sequential-id/create-sequential-id.spec.js
- packages/react/modules/helpers/create-sequential-id/create-sequential-id.ts
- packages/react/modules/helpers/create-sequential-id/index.ts
- packages/react/modules/helpers/index.ts
- packages/react/modules/index.ts
To strike a balance between Firefox crashing and memoizing adapter args only fo reach instance of configuration.
> Fix to add sequential id when testing multiple configurations at once

- packages/react-broadcast/modules/hooks/index.ts
- packages/react-broadcast/modules/hooks/use-feature-toggles/index.ts
- packages/react-broadcast/modules/hooks/use-feature-toggles/use-feature-toggles.spec.js
- packages/react-broadcast/modules/hooks/use-feature-toggles/use-feature-toggles.ts
- packages/react-broadcast/modules/index.ts
- readme.md
Adds a `useFeatureToggles` to `react-broadcast` returning an `boolean[]` when passed `{ [flagName: FlagName]: FlagVariation }`.
An alternative API would have been nested touples in `[ [FlagName, FlagVariation] ]`. This however felt a bit against the existing types where they guided to a hopefully consistent API over all.
> feat(react-broadcast): add useFeatureToggles

- packages/react-redux/modules/ducks/status/index.ts
- packages/react-redux/modules/ducks/status/status.spec.js
- packages/react-redux/modules/ducks/status/status.ts
- packages/react-redux/modules/hooks/index.ts
- packages/react-redux/modules/hooks/use-adapter-status/index.ts
- packages/react-redux/modules/hooks/use-adapter-status/use-adapter-status.spec.js
- packages/react-redux/modules/hooks/use-adapter-status/use-adapter-status.ts
- packages/react-redux/modules/index.ts
Pulls useAdapterStatus into react package to expose it through both redux and broadcast variant.
> feat(react-redux): to add support for use-adpater-status

- packages/splitio-adapter/modules/adapter/adapter.spec.js
- packages/splitio-adapter/modules/adapter/adapter.ts
- packages/types/index.ts
Added the ability to pass custom attributes into splitio `getTreatments` function. Solves #942 
Add a new object under `options` that is `treatmentAttributes`. It will key spread into `getTreatments` along side the `key` from user.
I don't love copying the type into `@flopflip/types` for SplitIO.Attributes.. but I think it is better than `any`. Open to suggestions.
On a side note, I couldn't figure out how to get all the tests to pass locally. Received a lot of errors like:
```
packages/react-redux/modules/hooks/use-flag-variations/use-flag-variations.spec.js
● Test suite failed to run
Cannot find module '@flopflip/react' from 'use-flag-variations.ts'
However, Jest was able to find:
'./use-flag-variations.spec.js'
'./use-flag-variations.ts'
```
but the splitio adapter test passed :)
> feat(splitio): support custom attributes

- packages/launchdarkly-adapter/modules/adapter/adapter.spec.js
- packages/launchdarkly-adapter/modules/adapter/adapter.ts
- packages/types/index.ts
Exposes LaunchDarkly client
https://github.com/tdeekens/flopflip/issues/829
This allows us to call LD's `track()` method (as an example).
cc tdeekens
1. Keeping assumption that FlopFlip will control adapter version for now.
> feat(launch-darkly): expose launchdarkly client

- .github/workflows/test.yml
- jest.test.config.js
- throwing-console-patch.js
Wraps the console to throw when logging on CI while setting the env variable. This helps to found act warnings among other things.
> chore(ci): add throwing logger on CI

- packages/react/modules/components/configure-adapter/configure-adapter.spec.js
Turns out if you do that and disable specs the code outside of its but inside the describe runs which is super confusion for rtl cause it messes up your dom.
> fix test setup to not be outside of it statements

- packages/react-redux/modules/components/branch-on-feature-toggle/branch-on-feature-toggle.spec.js
- packages/react-redux/modules/components/configure/configure.spec.js
- packages/react-redux/modules/components/inject-feature-toggle/inject-feature-toggle.spec.js
- packages/react-redux/modules/components/inject-feature-toggles/inject-feature-toggles.spec.js
- packages/react-redux/modules/components/toggle-feature/toggle-feature.spec.js
- packages/react-redux/modules/hooks/use-adapter-status/use-adapter-status.spec.js
This avoids act warnings in the refactoring to RFCs.
> refactor: to always avait to avoid act warnings

- packages/react-broadcast/modules/components/configure/configure.tsx
- packages/react/modules/components/configure-adapter/configure-adapter.tsx
Last nite fun.
Using `useDebugValue` can help with debugging and in the DevTools quite a bit. As a result the code also get's some leaner and more consise.
> refactor: to use debug value more

- packages/localstorage-adapter/modules/adapter/adapter.ts
To improve responsiveness between tabs when changing flags on one tab and watching for the action on another tab, a quicker polling interval is required, but that started emitting lots of redux actions, filling up the log for Redux DevTools.  (our system also centrally logs all redux actions).
This change allows responding to flag changes between tabs faster by increasing `pollingInteral` (was 60 seconds) without broadcasting large amounts of unneeded redux actions.
Next steps after this pull request could be to change the default  `pollingInteral` for the `localstorage-adaptor` to `1000` ms.  Also correcting the name of that parameter to `pollingInterval`.
> feat(localstorage-adapter): Only emit flagStateChange when the flags change

- packages/localstorage-adapter/modules/adapter/adapter.spec.js
- packages/localstorage-adapter/modules/adapter/adapter.ts
Add tests for localstorage interactions
The tests use `jest.useFakeTimers()` to advance the timers and trigger the `localStorage` read.  I initially implemented it to pass as the behavior was before #1001. In a subsequent commit, changed to pass as intended.
This pull request doesn't change the adapter logic as the underlying issue was fixed in #1003, but I did use a different approach by putting `adapterState.flags = nextFlags` in `handleFlagsChange`, but that was reverted when I merged from `upstream/master`.  setting `adapterState.flags` before emitting `flagsStateChange` is probably more clear.
> fix(local-storage-adapter): add tests for flag update from localstorage

- packages/launchdarkly-adapter/modules/adapter/adapter.spec.js
- packages/launchdarkly-adapter/modules/adapter/adapter.ts
- packages/localstorage-adapter/modules/adapter/adapter.spec.js
- packages/localstorage-adapter/modules/adapter/adapter.ts
- packages/memory-adapter/modules/adapter/adapter.spec.js
- packages/memory-adapter/modules/adapter/adapter.ts
- packages/splitio-adapter/modules/adapter/adapter.spec.js
- packages/splitio-adapter/modules/adapter/adapter.ts
- packages/types/index.ts
Adds the notion of an initialization status to all adapters. No configure call returns the client anymore. This could be seen breaking but configure should never been called yourself.
The TAdapterInitializationStatus can be Succeeded or Failed and is very similar to the TAdapterSubscriptionStatus.
> feat: add initialization status to adapters

- packages/react/modules/components/configure-adapter/configure-adapter.tsx
- packages/types/index.ts
This builds on the previous PR to not set the status too eagerly if possible. It has a fallback mechanism to respect old adapters which don't resolve configuration or reconfiguration with a result of it.
> fix: to not set status too eagerly

- packages/react-broadcast/modules/components/branch-on-feature-toggle/branch-on-feature-toggle.tsx
- packages/react-broadcast/modules/components/configure/configure.tsx
- packages/react-broadcast/modules/components/inject-feature-toggles/inject-feature-toggles.tsx
- packages/react-broadcast/modules/components/toggle-feature/toggle-feature.tsx
- packages/react-redux/modules/components/branch-on-feature-toggle/branch-on-feature-toggle.tsx
- packages/react-redux/modules/components/configure/configure.tsx
- packages/react-redux/modules/components/inject-feature-toggles/inject-feature-toggles.tsx
- packages/react/modules/components/configure-adapter/configure-adapter.tsx
This pull request moves on with the new ESLint recommendation to only use readonly types. While doing so previously untyped parts of the code base are now also more strictly typed.
> refactor: to use only readonly types

- .changeset/rare-tools-tie.md
- packages/react-broadcast/modules/hooks/index.ts
- packages/react-broadcast/modules/hooks/use-flag-variation/index.ts
- packages/react-broadcast/modules/hooks/use-flag-variation/use-flag-variation.spec.js
- packages/react-broadcast/modules/hooks/use-flag-variation/use-flag-variation.ts
- packages/react-broadcast/modules/index.ts
- packages/react-redux/modules/hooks/index.ts
- packages/react-redux/modules/hooks/use-flag-variation/index.ts
- packages/react-redux/modules/hooks/use-flag-variation/use-flag-variation.spec.js
- packages/react-redux/modules/hooks/use-flag-variation/use-flag-variation.ts
- packages/react-redux/modules/index.ts
This pull request adds a `useFlagVariation`-hook which allows convienent access to flag variations without evaluating their "actual" variation.
```js
const variation = useFlagVariation('foo')
const isEnabled = variation === MY_VARIATION.VARIATION_A;
```
> feat: add use-flag-variation

- .changeset/fresh-pens-clean.md
- packages/launchdarkly-adapter/modules/adapter/adapter.ts
- packages/localstorage-adapter/modules/adapter/adapter.ts
- packages/memory-adapter/modules/adapter/adapter.ts
- packages/splitio-adapter/modules/adapter/adapter.ts
Flags might have been set locked/unsubscribed when flags are initially loaded from the SDK.
> fix: to check subscription of flag upon initial sdk fetch

- readme.md
Fixed the syntax on one of the examples for isAdapterConfigured
If you copy and paste from that example it doesn't work!
> Fix the syntax on isAdapterConfigured

- .changeset/wise-cats-turn.md
- packages/launchdarkly-adapter/src/adapter/adapter.ts
- packages/localstorage-adapter/src/adapter/adapter.ts
- packages/memory-adapter/src/adapter/adapter.ts
- packages/react-broadcast/src/hooks/use-flag-variation/use-flag-variation.ts
- packages/react-broadcast/src/hooks/use-flag-variations/use-flag-variations.ts
- packages/react-redux/src/hooks/use-flag-variation/use-flag-variation.ts
- packages/react-redux/src/hooks/use-flag-variations/use-flag-variations.ts
- packages/react-redux/src/hooks/use-update-flags/use-update-flags.ts
- packages/react-redux/src/hooks/use-update-status/use-update-status.ts
- packages/react/src/components/configure-adapter/configure-adapter.tsx
- packages/splitio-adapter/src/adapter/adapter.ts
- packages/types/src/index.ts
This fixes the `(): import('../../types')` issue which seems to be Babel adding them.
> fix: to not infer returns

- .changeset/happy-hornets-give.md
- packages/react/src/components/configure-adapter/configure-adapter.tsx
- packages/types/src/index.ts
- readme.md
JSX.Element can be less than React.ReactNode. ReactNode can be booleans and undefined. As a result it creates quite bloated types which cause the library to fail typechecking.
> fix: to simplify types of configure

- .changeset/chatty-horses-jog.md
- babel-plugin-package-version.js
- packages/graphql-adapter/src/adapter/adapter.spec.js
- packages/react-broadcast/package.json
- packages/react-broadcast/src/hooks/use-adapter-status/use-adapter-status.spec.js
- packages/react-redux/package.json
- packages/react/package.json
- packages/react/src/components/configure-adapter/configure-adapter.spec.js
- packages/test-utils/package.json
- yarn.lock
Re: https://twitter.com/tdeekens/status/1460559774966292482
Adjust tests to highlight problems in React 18.
I had a glance at how the "status" is handled. I've seen some subscription-like patterns so you probably need to use [`useSyncExternalStore`](https://github.com/reactwg/react-18/discussions/86) to avoid the tearing that now occurs in React 18.
Considering test results change depending on how focused tests are run (full suite, single file, single test etc) there's probably also some cleanup issue. If a test schedules a microtask that changes global state then this could affect subsequent test.
> test: react 18

- demo/src/App.js
This PR fixes TypeError in the demo.
TypeError occurs when launching the demo.
```
cjs.js:61 Uncaught TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at getKeys (cjs.js:61:1)
at mergeObject (cjs.js:86:1)
at deepmerge (cjs.js:117:1)
at mergeAdapterArgs (flopflip-react.browser.esm.js:56:1)
at flopflip-react.browser.esm.js:112:1
at flopflip-react.browser.esm.js:281:1
at flopflip-react.browser.esm.js:298:1
at invokePassiveEffectCreate (react-dom.development.js:23487:1)
at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
```
The error is different, but I think this PR closes #1418 since the demo works.
> fix: fix TypeError in the demo

- .changeset/stale-ads-play.md
- packages/adapter-utilities/index.ts
- packages/combine-adapters/index.ts
- packages/cypress-plugin/index.ts
- packages/graphql-adapter/index.ts
- packages/http-adapter/index.ts
- packages/launchdarkly-adapter/index.ts
- packages/localstorage-adapter/index.ts
- packages/localstorage-cache/index.ts
- packages/memory-adapter/index.ts
- packages/react-broadcast/index.ts
- packages/react-redux/index.ts
- packages/react/index.ts
- packages/sessionstorage-cache/index.ts
- packages/splitio-adapter/index.ts
- packages/types/index.ts
See https://github.com/tdeekens/flopflip/pull/1606#issuecomment-1082298998
The `index.ts` file is not needed anymore since using preconstruct. Removing it just to formally mark packages with unreleased changes.
> chore: bump all packages

- .changeset/friendly-insects-lick.md
- packages/react-broadcast/package.json
- packages/react-broadcast/src/components/configure/configure.tsx
- packages/react-broadcast/src/components/toggle-feature/toggle-feature.spec.js
- packages/react-broadcast/src/store/index.ts
- packages/react-broadcast/src/store/store.ts
- yarn.lock
This refactors react-broadcast's usage of state for flags and adapter status to move it into a small external store implementation. This then allows to use useSyncExternalStore which in turn makes flopflip ready for concurrent mode of React v18.
> refactor(broadcast): to use sync external store and concurrent mode 

- .changeset/tough-chefs-lie.md
- packages/react/src/components/configure-adapter/configure-adapter.spec.js
- packages/react/src/components/configure-adapter/configure-adapter.tsx
Ohterwise internally set adapterArgs through reconfigure are always overwritten by the adapterArgs passed by props.
> fix: to not overwrite internally set adapter args

- .changeset/six-toes-double.md
- packages/launchdarkly-adapter/src/adapter/adapter.spec.js
- packages/launchdarkly-adapter/src/adapter/adapter.ts
- packages/types/src/index.ts
LaunchDarkly released a v3 of their JS SDK. This supports a feature called contexts. More can be found in the [migration guide here](https://docs.launchdarkly.com/sdk/client-side/javascript/migration-2-to-3).
Generally, it's a non breaking change for the SDK but eventually the old "user only" context will be removed. Flopflip could also build this in a non breaking way. That however would be tricky and one can basically remain using an old version of the library.
> refactor: migrate ld adapter to allow contexts

- packages/http-adapter/src/adapter/adapter.ts
- packages/react-broadcast/src/components/configure/configure.tsx
- packages/react-broadcast/src/components/test-provider/test-provider.spec.js
- packages/react-broadcast/src/components/test-provider/test-provider.tsx
- packages/react-broadcast/src/hooks/use-adapter-status/use-adapter-status.ts
- packages/react-redux/src/components/configure/configure.tsx
- packages/react-redux/src/ducks/status/status.spec.js
- packages/react-redux/src/ducks/status/status.ts
- packages/react-redux/src/ducks/status/types.ts
- packages/react-redux/src/hooks/use-update-status/use-update-status.ts
- packages/react-redux/src/store/enhancer/enhancer.spec.js
- packages/react-redux/src/store/enhancer/enhancer.ts
- packages/react-redux/src/types.ts
- packages/react/src/components/adapter-context/adapter-context.spec.js
- packages/react/src/components/adapter-context/adapter-context.ts
- packages/react/src/components/configure-adapter/configure-adapter.tsx
- packages/types/src/index.ts
The adapter status is not kept correctly if multiple adapters are used. Essentially we need to kept the adapter state one per adapter.
> fix: adapter status state to be kept independently

- .changeset/moody-beds-rhyme.md
- packages/combine-adapters/src/adapter/adapter.spec.js
- packages/combine-adapters/src/adapter/adapter.ts
This wires up the underlying adapters now that the state above can handle keeping track of all adapters.
> fix(combine-adapters): status to connect underlying adapters

- .changeset/shiny-elephants-love.md
- .changeset/swift-parents-yell.md
- package.json
- packages/react-broadcast/package.json
- packages/react-broadcast/src/components/toggle-feature/toggle-feature.tsx
- packages/react-redux/src/components/toggle-feature/toggle-feature.tsx
- packages/react/package.json
- yarn.lock
This otherwise builds types with `React.JSX.Element` instead of `JSX.Element`. This is a breaking change for packages with resolutions.
> fix: build with older types

- .changeset/sweet-mirrors-punch.md
- packages/combine-adapters/src/adapter/adapter.ts
Otherwise this adapter often hands in state 1 instead of moving to 2.
> fix(combine-adapters): to be configured earlier

- .changeset/lucky-bears-hunt.md
- packages/graphql-adapter/CHANGELOG.md
- packages/graphql-adapter/src/adapter/adapter.ts
- packages/http-adapter/src/adapter/adapter.ts
- packages/launchdarkly-adapter/CHANGELOG.md
- packages/localstorage-adapter/CHANGELOG.md
- packages/localstorage-adapter/src/adapter/adapter.ts
- packages/splitio-adapter/CHANGELOG.md
- packages/types/CHANGELOG.md
- packages/types/src/index.ts
- readme.md
Closes https://github.com/tdeekens/flopflip/issues/1746
If used this is a breaking change. However, we're quite sure this argument is not set by anybody. Otherwise TypeScript should also help.
> fix: to rename pollingInteralMs to pollingIntervalMs

- .changeset/fair-knives-fetch.md
- packages/react-broadcast/src/hooks/use-adapter-status/use-adapter-status.ts
- packages/react-redux/src/ducks/status/status.spec.js
- packages/react-redux/src/ducks/status/status.ts
- packages/react-redux/src/hooks/use-adapter-status/use-adapter-status.ts
- packages/react/src/components/adapter-context/adapter-context.spec.js
- packages/react/src/components/adapter-context/adapter-context.ts
Allows fetching the status of one adapter from the system.
> feat: allow use-adapter-status to fetch status of one adapter

- .changeset/sweet-flies-smoke.md
- packages/types/src/index.ts
This PR makes the `flags` arg of `TLaunchDarklyAdapterArgs` optional.
When configuring `<ConfigureFlopFlip />` with the launchdarkly adapter, you are unable to configure the adapter without the `flags` arg. Making the `flags` arg optional allows you to configure the adapter without explicitly providing flags.
This seems like the intended behavior, because there is a conditional check [here](https://github.com/tdeekens/flopflip/blob/d194e41c68e9c29b85c11c8682eb45ff9b8711d7/packages/launchdarkly-adapter/src/adapter/adapter.ts#L161-L162) that gets all flags if the `flags` arg is not provided.
> fix(launchdarkly-adapter): Make flags arg optional in TLaunchDarklyAdapterArgs type definition

- .changeset/lucky-ducks-develop.md
- packages/react-broadcast/src/hooks/index.ts
- packages/react-broadcast/src/index.ts
- packages/react-redux/src/hooks/index.ts
- packages/react-redux/src/index.ts
Export `useAllFeatureToggles` hooks.
In the [previous release](https://github.com/tdeekens/flopflip/releases/tag/v13.2.0) we included a couple of new hooks but I forgot to actually export them so consumers can't access to them 🤦 .
This PR just adds them to the corresponding export files.
> Export `useAllFeatureToggles` hooks

- .changeset/weak-pots-melt.md
- packages/combine-adapters/src/adapter/adapter.spec.js
- packages/react-broadcast/package.json
- packages/react-broadcast/src/hooks/use-all-feature-toggles/use-all-feature-toggles.spec.js
- packages/react-broadcast/src/hooks/use-all-feature-toggles/use-all-feature-toggles.ts
- packages/react-redux/package.json
- packages/react-redux/src/hooks/use-all-feature-toggles/use-all-feature-toggles.spec.js
- packages/react-redux/src/hooks/use-all-feature-toggles/use-all-feature-toggles.ts
- packages/test-utils/src/index.js
- pnpm-lock.yaml
Kudos to @CarlosCortizasCT for finding this bug.
We reversed the React context in place. Turns out you can do that 😓.
The commits for each package contain a broken test suite and then the fix. Sort of Uni-style TDD to prove the point.
The setup of how we test had to be adjusted as we want to test this with combined adapters.
> Fix reversing adapter identifiers in place

- .changeset/sweet-lemons-fold.md
- packages/http-adapter/src/adapter/adapter.ts
- packages/types/src/index.ts
When reconfiguring the adapterArgs can be passed into execute again. This helps passing new values to the underlying fetch.
> feat(http-adapter): to fetch adapterArgs to execute

- .changeset/chilled-phones-greet.md
- packages/cache/package.json
- packages/cache/src/cache/cache.spec.js
- packages/cache/src/cache/cache.ts
- packages/cache/src/cache/index.ts
- packages/cache/src/index.ts
- packages/cache/tsconfig.json
- packages/cache/tsconfig.lint.json
- packages/graphql-adapter/package.json
- packages/graphql-adapter/src/adapter/adapter.spec.js
- packages/graphql-adapter/src/adapter/adapter.ts
- packages/http-adapter/package.json
- packages/http-adapter/src/adapter/adapter.spec.js
- packages/http-adapter/src/adapter/adapter.ts
- packages/launchdarkly-adapter/package.json
- packages/launchdarkly-adapter/src/adapter/adapter.spec.js
- packages/launchdarkly-adapter/src/adapter/adapter.ts
- packages/launchdarkly-adapter/src/adapter/index.ts
- packages/react/package.json
- packages/react/src/components/configure-adapter/configure-adapter.spec.js
- packages/react/src/components/configure-adapter/configure-adapter.tsx
- packages/types/src/index.ts
- pnpm-lock.yaml
- readme.md
Relates to #1879
This introduces the behaviour of eager and lazy cache modes. At the same time it removes the `subscribeToFlagChanges` as we always subscribe. Lastly, the `unsubscribeFromCachedFlags` is almost like the lazy cache.
> feat: to add cache-mode to adapter

- .changeset/twenty-cherries-call.md
- packages/http-adapter/src/adapter/adapter.spec.js
- packages/http-adapter/src/adapter/adapter.ts
- packages/launchdarkly-adapter/src/adapter/adapter.ts
The `launchdarkly-adapter` does not perform any action with reconfiguring on an unchanged user context.
The `http-adapter` should perform similar. We do not need to empty the cache and refetch. We can just perform no action in this case.
> fix(http-adapter): to not empty flags with unchanged reconfiguration

- .changeset/modern-fireants-reflect.md
- packages/cache/src/cache/cache.spec.js
- packages/cache/src/cache/cache.ts
- packages/cache/src/cache/index.ts
- packages/cache/src/index.ts
- packages/graphql-adapter/src/adapter/adapter.spec.js
- packages/graphql-adapter/src/adapter/adapter.ts
- packages/http-adapter/src/adapter/adapter.spec.js
- packages/http-adapter/src/adapter/adapter.ts
- packages/launchdarkly-adapter/src/adapter/adapter.spec.js
- packages/launchdarkly-adapter/src/adapter/adapter.ts
This refactors the cache's key for flags to be a hashed version of the adapter's context.
When caching lazily it is important to fall back to a hot cache as often as possible. Otherwise a user would be served a stale cache for flags.
Taking for example the flow of:
1. User logs in
2. Views project A
3. In project A feature is enabled
4. User navigates to project B
5. In project B feature is disabled
With a lazy acting cache, in the above flow the user at 5. would still see an enabled feature. This is rooted in the fact that the cache does not synchronize its state until another hard reload (or unmounting of flopflip). 
The reason for this behaviour is that at any point flopflip's cache is bound - without this change - to a user's key. Any user can only have one set of cached flags. 
This …
> refactor: cache keys to be bound to adapter context

- .changeset/dull-turtles-thank.md
- .github/renovate.json
- package.json
- packages/cypress-plugin/package.json
- packages/react-broadcast/package.json
- packages/react-redux/package.json
- packages/react-redux/src/ducks/flags.ts
- packages/react-redux/src/ducks/index.ts
- packages/react-redux/src/ducks/status.ts
- packages/react-redux/src/enhancer.ts
- packages/react-redux/src/index.ts
- packages/react-redux/test/ducks/flags.spec.js
- packages/react-redux/test/ducks/status.spec.js
- packages/react-redux/test/test-utils.js
- packages/react/package.json
- pnpm-lock.yaml
- readme.md
Migrates to RTK to support redux v5 and react-redux v9 with standard patterns.
> Refactor to use redux-toolkit
